import mongoose from 'mongoose'

const ProfileSchema = new mongoose.Schema({
  id:                 { type: String, required: true, unique: true },
  firstName:          String,
  lastName:           String,
  gender:             String,
  dateOfBirth:        String,
  age:                Number,
  country:            String,
  city:               String,
  height:             Number,
  email:              String,
  phone:              String,
  college:            String,
  degree:             String,
  income:             Number,
  company:            String,
  designation:        String,
  maritalStatus:      String,
  languages:          [String],
  siblings:           String,
  caste:              String,
  religion:           String,
  wantsKids:          String,
  openToRelocate:     String,
  openToPets:         String,
  dietaryPreference:  String,
  drinkingHabits:     String,
  smokingHabits:      String,
  familyType:         String,
  familyValues:       String,
  manglik:            String,
  relationshipIntent: String,
  hobbies:            [String],
  profilePhoto:       String,
  status:             { type: String, default: 'Active' },
}, { timestamps: true })

export default mongoose.model('Profile', ProfileSchema)